feat: update module version and readme
Mint-System/Odoo-Apps-Account-Financial-Reporting pull request #2
Opened 2024-08-20 12:47 UTC by laszlokr

2024-08-23 08:12 UTC, laszlokr commented
@janikvonrotz not sure how to test this module, could you please give some pointers

2024-08-26 09:02 UTC, janikvonrotz requested changes
Test instructions: Create the general ledger report and check if contra account is shown.

2024-08-26 09:04 UTC, janikvonrotz requested changes

2024-08-26 09:04 UTC, janikvonrotz commented on account_financial_report_contra_accounts/report/general_ledger.py
> +        res["contra_accounts"] = move_line["contra_accounts"]
Check if this methods are still working.

2024-09-10 13:49 UTC, janikvonrotz approved these changes

2024-09-10 13:50 UTC, merged