feat: update module and readme
Mint-System/Odoo-Apps-Account-Financial-Reporting pull request #3
Opened 2024-08-20 12:54 UTC by laszlokr

2024-08-23 08:13 UTC, laszlokr commented
@janikvonrotz this one is also not clear how to test

2024-08-26 08:54 UTC, janikvonrotz requested changes
Test instructions are missing.

2024-08-26 08:54 UTC, janikvonrotz commented on account_financial_report_show_grouped_none/README.rst
> +Account Financial Report  Show Grouped None
There are two spaces.

2024-09-09 15:16 UTC, janikvonrotz approved these changes

2024-09-09 16:18 UTC, merged